arb-dir: lib/shared/l10n
template-arb-file: app_az.arb
output-dir: lib/generated/l10n
#output-dir: app_localizations.dart
synthetic-package: false
nullable-getter: false
untranslated-messages-file: untranslated.txt

